### ISSUE TITLE
Can you add the Welsh Azure User Group to the list

### ISSUE THREAD

**Issue by jonnychipz** [weeyin83/azureusergroup#4]
Hiya Sarah, Hope you are well!

Is there any chance you could add the Welsh Azure User Group to the list of UK User Groups.
Meet Up: https://www.meetup.com/MSFT-Stack/
Twitter: http://www.twitter.com/welshazure
LinkedIn: https://www.linkedin.com/groups/13866357/
Let me know if you need any more info from me in order to add!

Thank You
John

**Comment by weeyin83** [comment]
Thanks @jonnychipz, the Welsh Azure User Group is now listed. :)

**Comment by jonnychipz** [comment]
Thank You! 👍
